// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Configuración automática de Firebase para las plataformas soportadas en este proyecto.
/// 
/// Este archivo vincula la aplicación Flutter con el proyecto 'contract-manager-2026'
/// utilizando las credenciales específicas de cada plataforma.
class DefaultFirebaseOptions {
  
  /// Evalúa la plataforma actual y devuelve las [FirebaseOptions] correspondientes.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions no ha sido configurado para Web en este proyecto.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'Configuración para iOS no disponible. Ejecute FlutterFire CLI para configurar.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'Configuración para macOS no disponible.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Configuración para Windows no disponible.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Configuración para Linux no disponible.',
        );
      default:
        throw UnsupportedError(
          'La plataforma actual no tiene soporte configurado en Firebase.',
        );
    }
  }

  /// Configuración de Firebase para la plataforma Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqoZcU8rBZaAgrzihkRmvvV2M65srq8N8',
    appId: '1:1021008762765:android:e3d66a30d7053d93448fc4',
    messagingSenderId: '1021008762765',
    projectId: 'contract-manager-2026',
    storageBucket: 'contract-manager-2026.firebasestorage.app',
  );
}